<?xml version="1.0"?>
<!DOCTYPE items [
<!ELEMENT items (item*)>
<!ELEMENT item (id,text)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT ipAddr (#PCDATA)>
]>
<items>
    {% for item in items %}
        <item>
            <id>{{item.id}}</id>
            <text>{{item.text}}</text>
            <text>{{item.time}}</text>
        </item>
    {% endfor %}
</items>
